const CARDS = [
  { front: "dopiero", back: "только, лишь\nPrzykład: Przyszedłem dopiero wczoraj.", hint: "" },
  { front: "nadal", back: "всё ещё\nPrzykład: On nadal mieszka w Warszawie.", hint: "" },
  { front: "przynajmniej", back: "по крайней мере\nPrzykład: Spróbuj przynajmniej trochę.", hint: "" },
  { front: "właśnie", back: "как раз, именно\nPrzykład: To jest właśnie то, czego potrzebuję.", hint: "" },
  { front: "czasami", back: "иногда\nPrzykład: Czasami oglądam telewizję.", hint: "" },
  { front: "rzadko", back: "редко\nPrzykład: On rzadko się uśmiecha.", hint: "" },
  { front: "prawie", back: "почти\nPrzykład: Prawie skończyłem pracę.", hint: "" },
  { front: "od razu", back: "сразу\nPrzykład: Zrozumiałem od razu.", hint: "" },
  { front: "wkrótce", back: "вскоре\nPrzykład: Spotkamy się wkrótce.", hint: "" },
  { front: "doprawdy", back: "действительно\nPrzykład: To jest doprawdy dziwne.", hint: "" },
  { front: "chyba", back: "наверное\nPrzykład: Chyba pada deszcz.", hint: "" },
  { front: "pewnie", back: "конечно, наверное\nPrzykład: Pewnie masz rację.", hint: "" },
  { front: "raczej", back: "скорее, пожалуй\nPrzykład: To raczej не jest dobry pomysł.", hint: "" },
  { front: "właściwie", back: "вообще-то, собственно\nPrzykład: Właściwie то не wiem.", hint: "" },
  { front: "dokładnie", back: "точно, именно так\nPrzykład: Dokładnie o to mi chodzi.", hint: "" },
  { front: "zupełnie", back: "совершенно\nPrzykład: To zupełnie nowa sytuacja.", hint: "" },
  { front: "naprawdę", back: "действительно, правда\nPrzykład: To naprawdę piękne miejsce.", hint: "" },
  { front: "po prostu", back: "просто\nPrzykład: To jest po prostu łatwe.", hint: "" },
  { front: "akurat", back: "как раз, именно\nPrzykład: Akurat wtedy byłem w domu.", hint: "" },
  { front: "jednak", back: "однако\nPrzykład: Chciałem iść, jednak zostałem.", hint: "" },
  { front: "mimo to", back: "несмотря на это\nPrzykład: Było ciężко, mimo to udało się.", hint: "" },
  { front: "zatem", back: "итак, следовательно\nPrzykład: Zatem zaczynajmy.", hint: "" },
  { front: "więc", back: "значит, итак\nPrzykład: Było późно, więc poszedłem spać.", hint: "" },
  { front: "potem", back: "потом\nPrzykład: Najpierw obiad, potem spacer.", hint: "" },
  { front: "następnie", back: "затем\nPrzykład: Najpierw spotkanie, następnie kolacja.", hint: "" },
  { front: "obecnie", back: "в настоящее время\nPrzykład: Obecnie pracuję zdalnie.", hint: "" },
  { front: "dopóki co", back: "пока что\nPrzykład: Jest dobrze, dopóki co.", hint: "" },
  { front: "ciągle", back: "постоянно, всё время\nPrzykład: On ciągle o tym mówi.", hint: "" },
  { front: "stale", back: "непрерывно\nPrzykład: Stale rośnie liczba użytkowników.", hint: "" },
  { front: "wciąż", back: "всё ещё\nPrzykład: Wciąż czekam на odpowiedź.", hint: "" },
  { front: "natomiast", back: "зато, а вот\nPrzykład: Nie lubię kawy, natomiast herbatę uwielbiam.", hint: "" },
  { front: "tymczasem", back: "тем временем\nPrzykład: Tymczasem w domu panował spokój.", hint: "" },
  { front: "przede wszystkim", back: "прежде всего\nPrzykład: Przede wszystkim musimy быть spokojni.", hint: "" },
  { front: "co najmniej", back: "как минимум\nPrzykład: Potrzebuję co najmniej godziny.", hint: "" },
  { front: "zupełnie inaczej", back: "совсем иначе\nPrzykład: Wygląda to zupełnie inaczej niż wcześniej.", hint: "" },
  { front: "nigdy", back: "никогда\nPrzykład: Nigdy tego не widziałem.", hint: "" },
  { front: "wszędzie", back: "везде\nPrzykład: Szukaliśmy wszędzie.", hint: "" },
  { front: "gdzieś", back: "где-то\nPrzykład: Musiałem to zostawić gdzieś w biurze.", hint: "" },
  { front: "ani trochę", back: "ни капли\nPrzykład: Nie jestem ani trochę zmęczony.", hint: "" },
  { front: "od dawna", back: "давно\nPrzykład: Znamy się od dawna.", hint: "" },
  { front: "wreszcie", back: "наконец\nPrzykład: Wreszcie się udało.", hint: "" },
  { front: "na pewno", back: "наверняка, точно\nPrzykład: To się na pewno wydarzy.", hint: "" },
  { front: "przypadkiem", back: "случайно\nPrzykład: Spotkaliśmy się przypadkiem.", hint: "" },
  { front: "dopóki", back: "пока (не)\nPrzykład: Poczekaj tutaj, dopóki не wrócę.", hint: "" },
  { front: "ledwo", back: "едва\nPrzykład: Ledwo mogę oddychać.", hint: "" },
  { front: "najwyraźniej", back: "очевидно\nPrzykład: Najwyraźniej się pomyliłem.", hint: "" },
  { front: "без wątpienia", back: "без сомнения\nPrzykład: To jest без wątpienia ważne.", hint: "" },
  { front: "znowu", back: "снова, опять\nPrzykład: On znowu się spóźnił.", hint: "" },
  { front: "od niedawna", back: "недавно\nPrzykład: Mieszkam tu od niedawna.", hint: "" },
  { front: "w dodatku", back: "вдобавок, к тому же\nPrzykład: Było zimno, a w dodatku padał deszcz.", hint: "" },
];
export default CARDS;
